# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: audio.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61udio.proto\"\x16\n\x07\x43ontrol\x12\x0b\n\x03sig\x18\x01 \x01(\t\"\x15\n\x05\x43hunk\x12\x0c\n\x04wave\x18\x01 \x01(\x0c\x32\x33\n\tPlayAudio\x12&\n\x0eStartListening\x12\x08.Control\x1a\x06.Chunk\"\x00\x30\x01\x62\x06proto3')



_CONTROL = DESCRIPTOR.message_types_by_name['Control']
_CHUNK = DESCRIPTOR.message_types_by_name['Chunk']
Control = _reflection.GeneratedProtocolMessageType('Control', (_message.Message,), {
  'DESCRIPTOR' : _CONTROL,
  '__module__' : 'audio_pb2'
  # @@protoc_insertion_point(class_scope:Control)
  })
_sym_db.RegisterMessage(Control)

Chunk = _reflection.GeneratedProtocolMessageType('Chunk', (_message.Message,), {
  'DESCRIPTOR' : _CHUNK,
  '__module__' : 'audio_pb2'
  # @@protoc_insertion_point(class_scope:Chunk)
  })
_sym_db.RegisterMessage(Chunk)

_PLAYAUDIO = DESCRIPTOR.services_by_name['PlayAudio']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONTROL._serialized_start=15
  _CONTROL._serialized_end=37
  _CHUNK._serialized_start=39
  _CHUNK._serialized_end=60
  _PLAYAUDIO._serialized_start=62
  _PLAYAUDIO._serialized_end=113
# @@protoc_insertion_point(module_scope)
